#+TITLE: Abid Khan Sahib Speech at PA Smminar Feb 17, 2018
#+AUTHOR: --

* Raw Notes
- Sultan-Ul-Qalam Waqf-e-Nau.
- Impossible to be an orphan due to Khilafat
- Huzoor spent time doing interviews, but Huzoor missed his Jamaat.
- We represent Jamaat, our conduct reflects the Jamaat
  - If we are truthful, decent, that reflects on Jamaat. Our weakness,
    lackness of Namaz also reflects on Jamaat.
  - When Kieth Wilders from Holland villified Islam Huzoor warned him
    about his destruction, Abid Khan Sahib wrote up the press
    release. But forgot the "with prayers" part. 
- On a personal level, we don't do anything that causes problems for
  Jamaat, as we are representing the Jamaat. 
- The most basic requirement is to speak with humility. We can not
  speak off the cuff.
  - Huzoor frequently dictates to Abid Khan Sahib, and sometimes
    Huzoor talks for 12-13 or 14 minutes, you can see the he is being
    guided by Allah.
  - Sometimes Huzoor will pull out books, articles and other material,
    this shows the value of research.
- If we're not humble, we will not succeed.
  - Allah turns hearts, be humble, do not think "I am something".
- Huzoor's speech in Canad got a standing ovation.
  - Huzoor did not bask in the light.
  - Others would have thought "this is my time".
  - But Huzoor showed humility.
  - Huzoor stood up, kept his eyes down and returned to his chair as
    quickly as possible.
  - People say to Huzoor, now I know why you are a Khalifa, Huzoor
    responds with "I still do not know why."
- After an attack on a ghair Ahmadi mosque, we were sent to defend Islam
  - Non-Ahmadi Muslims asked "Why are Ahmadi's here?" and my staff
    started feeling threathened.
  - I seeked Huzoor's guidance, that they fear for their physical
    safety, and if they should come back.
  - Huzoor was surprised I had raised this, they must not come back in
    fear.
  - Huzoor instructed to buy flowers, which my staff did.
  - The police noticed the staff members carrying flowers, and they
    were asked to lead the procession.
- We should always be humble, and do not need to exagerate.
  - We wanted to attract more media attention to UK Jalsa.
  - Based on projection we decided to increase the numbers from last
    year.
  - Huzoor became unhappy, there is no need for use to exagerate.
  - That year we had our best covarage.
- We are dispensible, we should not think we are not.
  - Khilafat is not dispensible, and will succeed without us.
- Huzoor's Love, On a visit Huzoor's became unwell
  - Initial plan was three days of rest
  - But Huzoor cancelled those, stating "Ahmadi's want to meet me."
  - On another incident, an Ahmadi said that they were hoping Huzoor
    could have stayed outside longer.
  - When I asked him, he responded with "Age is also a factor."
  - Huzoor returned to lead prayers.
- Pray for Huzoor's health and our attachment.
- Tomorrow does not need to be a mystery, due to our attachment to the
  Quran and to Khilafat.
- Summary of meeting, "I was not interested on response, I was
  interested in what we said."





* The Summary

The main subject of Abid Bhai's speech was Khilafat and Huzoor. He
gave many examples of Huzoor's love for the Jamaat. At one point Huzoor
was giving non-stop interviews and a reporter pointed out to him, that
his day was long. Huzoor replied back by saying, this is not a long
day, but I am missing my Jamaat. 

We represent that Jamaat and we represent Huzoor, our conduct reflects
the Jamaat and our beloved Huzoor. If we are truthful, and decent,
this reflects on the Jamaat. Our weaknesses, and lackness in prayers
also reflects on Jamaat. When Keith Wilders of Holland villified
Islam, Huzoor warned him that he would be destroyed. When Abid Bhai
wrote up the press release and showed it to Huzoor, Huzoor replied,
you forgot the "with prayers part, you will be destroyed with
prayers." We must not do anything on a personal level that will cause
problems for Jamaat, as we are always representing the Jamaat. 

The most basic requirement that we must inculcate is humility. We can
not speak off the cuff. Even Huzoor does not speak off the cuff. When
preparing for a speech, there are times that Huzoor dictates 14
minutes straight, and you feel that he is divinely guided. But there
are other times, where he will pull out books and articles and other
material. This shows that Huzoor values research. If we are not humble
we will not succeed. Allah is the only being that can turn hearts, do
not think "I am something." We should always be humble, we do not need
to exaggerate. Another example came when we wanted to increase the
media coming to the Jalse. We exaggerated the expected number of
people coming to Jalsa from last year. Huzoor was unhappy, Huzoor said
there is no need to exaggerate. That year we got the best coverage. We
should always be humble. We are dispensible, even without us
Ahmadiyyat will succeed. Khilafat is not depensible, and will succeed
without us.

We should reflect Huzoor's humble nature. When Huzoor received a
standing ovation in Canada, Huzoor did not bask in the light. Even
though we would have, we would have felt like "this is my time". Even
then, Huzoor showed humility. Huzoor stood up kept his eyes down and
quickly returned to his chair. *NEED TO EXPAND WITH* ... "I still do
not know why I was chosen as Khalifa..." *Information Needed*

We should try to reflect Huzoor's love for the Jamaat and
Ahmadis. After an attack on a ghair Ahmadi mosque, Huzoor sent the
press team. The non-Ahmadi Muslims started asking "Why are Ahmadis
here?" and the Ahmadis started feeling threathened. They asked Huzoor
whether they could return as they feared for their physical
safety. Huzoor was suprised by the request, he said that they must not
come back. He further instructed them them to take flowers. When the
press team got some flowers, they were noticed by some polce
officers. The police officers told them that since you have the
flowers, you should lead the procession about to start. 

We should return our love for Huzoor as well. On a visit, Huzoor
became unwell, and initially there were three days of break
scheduled. Huzoor cancelled these three days and scheduled meetings
with Ahmadis, stating that "Ahmadis want to meet me." On another
incident while visiting another Jamaat, Huzoor had exited the caravan
and quicker then usual went inside. The Ahmadis outside were hoping
that Huzoor would have stayed outside longer. When this was brought to
Huzoor, he stated "age is also a factor". 

Pray for Huzoor's health and our attachment to Huzoor. The quote
“Yesterday is history, tomorrow is a mystery, today is a gift of God,
which is why we call it the present.” is inaccurate because due to our
attachment to the Quran and Khalifa makes tomorrow need not be a
mystery. Please humbly pray for Huzoor. 

