#+TITLE: Tajneed Guidelines
#+AUTHOR: MKA Tajneed Department


* Introduction
The MKA Tajneed Department is responsible for maintaining accurate
and updated information of Khaddam, regardless of the level of
participation in Jamaat or Khuddam Programs. Both active and
inactive members are included in official Tajneed.

The MKA Tajneed is now a part of the National Tajneed. This means that
there is only one place where member information is
stored. Individuals that can make updates to this database are
limited. This document serves as a guideline to the different branches
on proper procedures.
  
* Tajneed Update Process
** Individuals
*** Same Majlis
If your or your family are moving locally within the same Majlis.
1. Update your new information on the Tajneed Website must update your
   new address with local secretary as well as online
*ADD SITE INFORMATION*.
*** Different Majlis
In addition to
** Local Nazimeem

** Regional and National Muhtamim 

* Tajneed Issues
** An individual has lost contact with Jamaat
Removing an individual from Tajneed has serious implications. Proper
actions must be taken to ensure a mistake is not made. There are
certain guidelines to what is considered and inactive member:

1. *ATTENDANCE* Requirements
2. *CHANDA* Requirements
3. *OTHER* Requirements

These are delicate steps and should be taken with great care. Before
removing an individual from the Tajneed ensure the following *REVIEW*:
1. Contact has been made with the individual, and problems or concerns
   are highlighted. This should ideally be done with Qaid Sahib as
   well as parties involved.
2. Contact has been made to highlight to the individual the
   implications of this decision.
3. Reaching out to national level to proceed.
4. Permission sought from Hazur.

** An individual is lost and not known
1. Proper channels used to find the individual.
2. Contact made.
3. *SECTION NEEDS EXPANSION*


* Reference and Resources
** Tajneed Website
** Regional Nazimeen Contact
** Nation Muhtamim Contact
