#+TITLE: Tajneed Guidelines
#+AUTHOR: MKA Tajneed Department


* Introduction
The MKA Tajneed Department is responsible for maintaining accurate
and updated information of Khaddam, regardless of the level of
participation in Jamaat or Khuddam Programs. Both active and
inactive members are included in official Tajneed.

The MKA Tajneed is now a part of the National Tajneed. This means that
there is only one place where member information is
stored. Individuals that can make updates to this database are
limited. This document serves as a guideline to the different branches
on proper procedures.

Tajneed Information is used in the following ways:
- To share information about Huzoor's instructions, events, campaigns etc.
- To plan and register for local and national events like Jalsa.
- To create accurate finance budgets which help plan for various projects.
- To pay chanda and get it recorded properly. 
  
* Tajneed Update Process
** Individual
The individual Tajneed update process is straightforward. All forms
can be found at [2] in the references section. The forms are divided
into the following categories:

*** New/Change Membership Information
If you are new to the USA, you should use form T1 to be assigned a
Member ID Code. This code is unique to each individual.

*** Change of Address
If your or your family are moving locally within the same Majlis. You
must update your new address with local secretary as well as
online. You should submit Tajneed Form T2.

*** Newborn Information
If you recently had a child, you should submit form T3 to
get a new Member Code for him/her.

*** New Convert
If someone is converting from a different faith, they must complete a
T4 Bait form. 

*** Jamaat ID Card
To order Jamaat ID Cards, please complete the T7 form. 

** Local Regional and National Secretaries
If you are updating Tajneed information on someone's behalf, please
contact tajneed@ahmadiyya.us.


* Tajneed Issues
** An individual has lost contact with Jamaat
Removing an individual from Tajneed has serious implications. Proper
actions must be taken to ensure a mistake is not made. There are
certain guidelines to what is considered and inactive member:

1. *ATTENDANCE* Requirements
2. *CHANDA* Requirements
3. *OTHER* Requirements

These are delicate steps and should be taken with great care. Before
removing an individual from the Tajneed ensure the following *PLEASE REVIEW*:
1. Contact has been made with the individual, and problems or concerns
   are highlighted. This should ideally be done with Qaid Sahib as
   well as parties involved.
2. Contact has been made to highlight to the individual the
   implications of this decision.
3. Reaching out to national level to proceed.
4. Permission sought from Hazur.

Relating to Khadims less active then other, Huzoor has said [1]:
1. Active Khuddam must make sure they set high standards and are
   regular in coming to the Mosque. You can not preach to another
   person unless you yourself are observing what you require from them.
2. There is no benefit to being harsh or strict - rather people should
   be treated with love and compassion. They should be persuaded
   rather than forced into realizing the benefits of staying close to
   the Jamaat.
3. It is imperative that Ahmadis pray for their fellow brothers. 

** An individual has moved Auxilaries
If someone has moved from Tifl to Khadim, or Khadim to Ansar, the
local secretary must ensure that change is made. 

* Resources
** Regional Nazimeen Contact

** National Muhtamim Contact


* References 
[1] Abid Khan Singapoe Diary 2013: https://www.alislam.org/library/updates/singapore-tour-september-2013-a-personal-account/ 

[2] Ahmadiyya Tajneed Information: https://www.ahmadiyya.us/tajneed-membership
