#+TITLE: Letters to Huzoor

* 19 February 2018 - Abid Khan Sahib's Presence at National PA Meeting

My beloved Huzoor, 

I hope this letter reaches you in good health and pray that Allah
strengthens your hand and that the blessing of Khilafat reach the
corners of the earth.

Abid Bhai's presence at the USA National Public Affairs Seminar was
deeply emotional. His speech and demeaner showed respect for Islam and
Khilafat. His words moved people to tears on more then one
occasion. His speech was eloquent and his voice was soft. He is a
gentle soul, but his words come out with such power they move the
room. Every part of his speech was focused on Khilafat. He does not
bring unneeded attention to himself either. His focus and direction
are towards you. There were a few times that I found his chair empty
on stage, and I never knew he had left or when he returned. He does
not bring any attention to himself, and lets other be in the front. It
is only your love he seeks.

I first heard Abid Bhai speak at the Yosemite Khuddam Ijtema. Even
then his respect for you was apparent. After the session, he was
surrounded by many members. Due to his popularity, I did not approach
him and regretted it. However, this time when he visited, Allah gave
me the courage to say Salam. Actually Allah gave me the opportunity to
say my Salam twice! Due to the people surrounding him, he ended
shaking my hand again. I think he was nervous. He wanted to make sure
he missed no one. He knew he was representing you. His love is truely
a reflection of your love.

Allah then gave me the courage to walk up to him a second time, and
ask "Do people make personal contact with you? Over email or such?",
he responded with "Yes, yes of course they do. Why don't you take my
Whatsapp number, but please don't share it with anyone." He did not
know me, or my background, yet he provided my his personal number. His
love for the Jamaat and Ahmadis overtook me.  

Another incident came during the internal session, we had a mock
interview session. The Public Affairs team has put together a flow
chart, which by the Grace of Allah, is efficient and well
organized. During the mock interview, I forgot the whole flow chart,
and my mind went blank. The time was up, I was embarrassed. While I
was walking away Abid Bhai texted me, "Well done in your interview."
Abid Bhai's words of encouragment resonated with me, his care and love
was apparent.

The third incident happened after namaz, I asked him how frequently I
should write to you. He asked "how often do you write now?" I didn't
reply. He responded "one month, two months? one year?", he asked "when
did you write last?", I said "a few days ago, before this meeting, I
also wrote in January, I am trying to write every month." He said,
"We'll see next january." I had disappointed him. He continued with,
"Write to Huzoor, he'll remember you. Huzoor remembers everyone who
writes to him." He loves you and he wants everyone to share in
that. He loves this Jamaat and wishes that everyone would
write.

Huzoor, I humbly request prayers for Abid Bhai and his family. After
interacting with him my heart felt love. My love for you, love for
him, love for my fellow brothers increased. Huzoor I pray that Abid
Bhai continue his wonderful work. May Allah bless him emmensely for
the love he shows this Jamaat. May Allah grant Abid Bhai and his
progeny a long and healthy life in the service of Khilafat. May Allah
forgive him, have mercy on him, guide him, and grant him security. May
Allah cover up his shortcomings, provide for him, and raise him
up. May Allah bless this Jamaat with more people that reflect your
love.

Huzoor words do not do justice to Abid Bhai's kind heart. Please pray
for him.









* Template
- Salutations
- Prayers for Huzoor
- Prayers for Jamaat
- Purpose
