name: Publish Org Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout org repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/org.git
          path: 'org'
          
      - name: Checkout github.io repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/monibahmed.github.io.git
          path: 'org/publish'
          
      - name: Setup Emacs
        run: |
          sudo apt update && sudo apt install emacs-nox -y

      - name: Build the site
        run: |
          cd org/publish
          emacs --script ./build-site.el

      - name: Push changes
        run: |
          cd org/publish
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add *
          git commit -m "Auto-update site"
          git push 
          
