name: Publish Org Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout org repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/org
          path: 'org'

      - name: Checkout monibahmed.github.io repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/monibahmed.github.io
          path: 'monibahmed.github.io'
          
      - name: Setup Emacs
        run: |
          sudo apt update && sudo apt install emacs-nox -y

      - name: Build the site
        run: |
          emacs --script ../build-site.el

      - name: Copy generated files to monibahmed.github.io
        run: |
          cp -r org/public/* monibahmed.github.io/

      - name: Push changes
        run: |
          cd monibahmed.github.io
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-update site"
          git push
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
