name: Publish Org Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout org repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/monibahmed.github.io@main
          token: ${{ secrets.PUBLISH_WEBSITE }}
          path: 'publish'
          
      - name: Setup Emacs
        run: |
          sudo apt update && sudo apt install emacs-nox -y

      - name: Build the site
        run: |
          emacs --script ./build-site.el

      - name: Push changes
        run: |
          cd publish
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-update site"
          git push https://${{ secrets.PUBLISH_WEBSITE }}@github.com/monibahmed/monibahmed.github.io.git main
          
