name: Publish Org Files to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github.io repository
        uses: actions/checkout@v2
        with:
          repository: monibahmed/monibahmed.github.io
          path: 'publish'
          token: $ {{ secrets.PUBLISH_WEBSITE }}
         
          
      - name: Setup Emacs
        run: |
          sudo apt update && sudo apt install emacs-nox -y

      - name: Build the site
        run: |
          cd publish
          emacs --script ./build-site.el

      - name: Push changes
        run: |
          cd publish
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "Auto-update site"
          git push 
          
